name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.0-nullsafety.0
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3
  cloud_firestore: ^1.0.0
  provider: ^5.0.0-nullsafety.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
